language: java
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb
    JAVA_LIBRARY_PATH=/usr/lib/jni
before_install:
- wget -N https://downloads.gradle.org/distributions/gradle-2.2.1-bin.zip
- unzip gradle-2.2.1-bin.zip
- export PATH=`pwd`/gradle-2.2.1/bin:$PATH
- sudo apt-get install -y --force-yes hdfview
after_success:
- gradle jacocoTestReport coveralls
